#!/usr/bin/env node
/**
 * Recompile the evidence contract and regenerate loadgen/contract.go in sync
 *
 * Usage (in the fiscobcos/ directory, requires Node.js 18+):
 *   npm install --no-save solc@0.8.11
 *   node scripts/compile_contract.mjs
 *
 * Outputs:
 *   contracts/compiled/SoftwareFactoryLogs.abi
 *   contracts/compiled/SoftwareFactoryLogs.bin
 *   loadgen/contract.go   (embeds the ABI and bytecode)
 *
 * After editing the .sol, remember to rebuild the load-test image:
 *   docker build -f loadgen/Dockerfile -t fisco-loadgen .
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import solc from 'solc';

const base = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const solPath = path.join(base, 'contracts', 'SoftwareFactoryLogs.sol');
const outDir = path.join(base, 'contracts', 'compiled');

const input = JSON.stringify({
  language: 'Solidity',
  sources: { 'SoftwareFactoryLogs.sol': { content: fs.readFileSync(solPath, 'utf8') } },
  settings: {
    optimizer: { enabled: true, runs: 200 },
    outputSelection: { '*': { '*': ['abi', 'evm.bytecode.object'] } },
  },
});

const output = JSON.parse(solc.compile(input));
const fatal = (output.errors || []).filter((e) => e.severity === 'error');
if (fatal.length) {
  console.error(fatal.map((e) => e.formattedMessage).join('\n'));
  process.exit(1);
}
const contract = output.contracts['SoftwareFactoryLogs.sol'].SoftwareFactoryLogs;
const abi = JSON.stringify(contract.abi);
const bin = contract.evm.bytecode.object;

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(path.join(outDir, 'SoftwareFactoryLogs.abi'), abi);
fs.writeFileSync(path.join(outDir, 'SoftwareFactoryLogs.bin'), bin);

// Regenerate loadgen/contract.go in sync (single-quoted string concatenation
// avoids backtick-escaping issues inside template literals)
const BT = String.fromCharCode(96); // backtick
const TAB = String.fromCharCode(9); // tab
const go = [
  '// Code generated by solc 0.8.11 (contracts/compiled), DO NOT EDIT.',
  '// Contract source: contracts/SoftwareFactoryLogs.sol',
  '// Recompile: node scripts/compile_contract.mjs',
  'package main',
  '',
  '// SoftwareFactoryLogsABI contract ABI (generated by solc --abi)',
  'const SoftwareFactoryLogsABI = ' + BT + abi + BT,
  '',
  '// SoftwareFactoryLogsBin deployment bytecode (generated by solc --bin, with 0x prefix)',
  'const SoftwareFactoryLogsBin = "0x' + bin + '"',
  '',
  '// LogRecord maps one-to-one to the contract struct LogRecord (Go field names are the camelCase form of the Solidity field names)',
  '// Used for the tuple encoding of abi.Pack("recordLog"/"recordLogChecked", rec, ...)',
  'type LogRecord struct {',
  TAB + 'Id          string',
  TAB + 'Category    string',
  TAB + 'Timestamp   uint64',
  TAB + 'Level       string',
  TAB + 'Message     string',
  TAB + 'UserId      string',
  TAB + 'Module      string',
  TAB + 'Project     string',
  TAB + 'Operation   string',
  TAB + 'Status      string',
  TAB + 'Endorsement string',
  '}',
  '',
].join('\n');
fs.writeFileSync(path.join(base, 'loadgen', 'contract.go'), go);

console.log(`✅ Compilation done`);
console.log(`  ABI:   contracts/compiled/SoftwareFactoryLogs.abi (${abi.length} chars)`);
console.log(`  Bytecode: ${bin.length / 2} bytes`);
console.log(`  Synced: loadgen/contract.go`);
